추가: feature/main-page 브랜치 생성
mju-likelion/raonair-frontend-legacy pull request #2
Opened 2021-08-04 08:51 UTC by skullkim

메인 페이지 구현 관련 브랜치

2021-08-04 12:16 UTC, ndaemy requested changes
.idea/ 는 .gitignore로 가시지요~

2021-08-05 12:47 UTC, ndaemy requested changes

2021-08-05 12:47 UTC, ndaemy commented on src/pages/HomePage.js
> +            </Background>
요럴땐 self-closing으로 처리해주시죠!

2021-08-05 12:47 UTC, ndaemy commented on .idea/workspace.xml
> -      <change beforePath="$PROJECT_DIR$/.idea/workspace.xml" beforeDir="false" afterPath="$PROJECT_DIR$/.idea/workspace.xml" afterDir="false" />
...? 메인 페이지에 환영 문구 추가한건 어디에..?

2021-08-05 12:49 UTC, ndaemy commented on src/pages/HomePage.js
> +    const [selectedTarget, setSelectedTarget] = useState('연극');
요런 화면상에 보이지 않을 state는 영문이 더 좋아요 ㅊㄱㅊㄱ

2021-08-05 12:50 UTC, ndaemy commented on src/pages/HomePage.js
> +    font-weight: normal;
tab 이 요녀석만 일정하지 않아요

2021-08-05 12:51 UTC, ndaemy requested changes
이거 이렇게 한다고 이미 들어간 .idea 폴더가 사라지진 않아요. .idea를 깃에서 한 번 빼주셔야 합니다.

2021-08-05 12:57 UTC, skullkim commented on src/pages/HomePage.js
> +            </Background>
background 컴포넌트 안에 다른 컴포넌트가 들어갈거여서 저렇게 해놓은건데 들어갈걸 알아도 커밋시에 없으면 self-closing해야 하나요?

2021-08-05 12:57 UTC, skullkim commented on src/pages/HomePage.js
> +    const [selectedTarget, setSelectedTarget] = useState('연극');
수정하겠습니다

2021-08-05 12:58 UTC, skullkim commented on src/pages/HomePage.js
> +    font-weight: normal;
수정하겠습니다

2021-08-11 15:19 UTC, ndaemy approved these changes

2021-08-11 15:22 UTC, merged